C_List = [
    {
        course: '結構生物資訊',
        eng_course: 'strubioinfo',
        year: '109-1',
        Dtag: 'DBT',
        proper_des: '對生物知識有基本了解、想了解生物資訊應用於蛋白質結構、藥物設計的原理與工具的人。若是外系生，最好不怕遇到陌生知識、且勇於問問題',
        teacher: '楊進木',
        des: '老師很ㄎㄧㄤ，使用板書跟PPT，但老師上課蠻跳的，需要努力跟上腳步(?)<br>這門課在電腦教室上，也會操作電腦、軟體等，老師上課會希望同學自行截圖使用軟體的過程。',
        info: '1. 這門課是生資所必修，，不需要程式能力（有當然好，但課堂不會寫程式），但最好要有一些生物的基本概念，（不過雖然有基本概念基本上也不一定聽得懂。） 上課前會問同學背景。如果真的不排斥聽聽看其實可以試試看，考試沒很難（對生資所來說xP，畢竟都是老師講過的），如果勇敢問旁邊的人問題、或問老師問題，可以嘗試；不然建議選其他課。 <br>2. 我那時候修的時候去年人不多，所以老師會一直問同學問題。 <br>3. 期末要挑一個感興趣的蛋白質，從sequence alignment 做到藥物預測，就算做不出什麼結果也沒關係，但只少要有簡單的自己的分析跟過程，老實說有點水，但身邊對生資沒很熟的同學修他類似的課會有點小吃力。',
        score_des: '數份作業（都不難，查網路都有）、一次期末考、一份期末報告',
        futurework: '這門課修完以後，如果有興趣的話可以修楊老師下學期的智慧藥物設計，或去修蕭育源老師的結構生物學，去更深的了解蛋白質結構的特性、分類等',
        cross_des: '生物資訊/計算生物',
        link: '',
        infolink: 'course/strubioinfo.html',
        author: '生科10 何家慈',
    },
    {
        course: "生理學",
        eng_course: "Physiology",
        year: "108-1.108-2",
        Dtag: "DBT",
        proper_des: "喜歡做動物實驗、想了解基本人體生理，或對普生的循環、呼吸、神經、肌肉等領域有興趣者",
        teacher: "曲在雯、林志生",
        intheclass: "曲在雯：上課方式較屬放射性思考，不會按照PPT或生理課本一頁一頁教，容易較跳tone。但整體上課充實，邏輯清晰。上課時不時會提出問題希望同學幫忙回答，老師總是面惡心善，在第一堂課加退選都會給下馬威，但是其實考試分數都不會給太低，注意如果他寫板書的話盡量往前做，因為他字有點小而且有時候潦草，坐太後面會看不懂。<br>\n林志生：很有趣的一個老師，都會準時下課而且滿為學生著想，他多上呼吸的部分，會帶一些器材給大家體驗，也會講他女兒的故事XD 有時候上課提到的一些東西例如藥廠、藥品、AED位置等等他都會放在考題裡面XD",
        info: "雖然上課很認真，老師感覺看起來不錯，但是實驗室並不輕鬆。當然如果是想提升挫折容忍力以及大幅提升實驗實力與行政辦事方法的話那或許是個好選擇",
        score_des: "大部分都是期中期末考，有時候會有加分作業，如果遇到太多假日的話，期中期末也有可能變成take home",
        futurework: "動物實驗、細胞實驗、神經生物類",
        cross_des: "神經生物",
        link: "",
        author: "fish"
        },
        {
        course: "材料力學",
        eng_course: "mechanics_of_materials",
        year: "109-2",
        Dtag: "ME",
        proper_des: "對材料最佳化結構設計以及力學分析有興趣的同學",
        teacher: "鄒年棣",
        intheclass: "老師使用平板書寫，並將書寫內容投放到螢幕上。<br>\n老師畫圖很漂亮，字也蠻好看的，計算題目時過程也是非常清楚。<br>\n上課會帶學生做非常多範例，如果有一邊跟著想的話，基本上不用複習，可以直接寫作業。<br>\n小考採線上，期中期末採紙筆測驗。",
        info: "老師非常有教學熱誠，回答學生問題時也是非常有耐心，遇到這位老師可以說材料力學的基礎可以被打得很紮實。本堂課需要會微積分和三角函數，至於工程數學只會用到一點(在用之前，老師會再複習一次)。\n老師給分不會太苛刻，我在不調分的情況下有85，調完後便91分。",
        score_des: "小考30%，期中期末70%",
        futurework: "大到房子的結構設計，小到微型針頭的設計都在材料力學的範疇，生活中的物品都是材料力學的結晶。材料力學不僅可以用來評估一項設計的可行性，同時也可以提前預測一個設計的可能使用壽命。雖然材料力學是一個非常基礎的學科，但是它卻是很多進階力學分析的基礎。",
        cross_des: "材料系必修",
        link: "https://www.facebook.com/groups/2714680181981495",
        author: "chun"
        },
        {
        course: "微生物學",
        eng_course: "microbiology",
        year: "107-1",
        Dtag: "DBT",
        proper_des: "有生物基礎知識即可，但有生化概念較佳",
        teacher: "蘭宜錚、彭慧玲、麥如村",
        intheclass: "上課用PPT",
        info: "我修的這年之前大部分是其他組合的老師，這次是第一次有蘭宜錚、麥如村老師加入。蘭老師講的很生化，基本上就是把生化再複習更透徹一點，其實如果原本有生化基礎的同學會修得蠻順利的；麥如村老師負責兩堂病毒相關的課；彭老師教微生物學很資深，基本上就是要背許多微生物名字跟功用，需要蠻多背誦的，但我覺得蠻有趣的xD。",
        score_des: "三～四次大考",
        futurework: "未來可修「醫學微生物」更了解特定微生物、病毒的相關知識；也可以修蘭老師（生物工程相關）、彭老師（細菌相關）的相關課程。",
        cross_des: "生物工程",
        link: "https://timetable.nycu.edu.tw/?r=main/crsoutline&Acy=107&Sem=1&CrsNo=1590&lang=zh-tw",
        author: "chiatzu"
        },
        {
        course: "計算生物概論",
        eng_course: "ComputationalBiology",
        year: "107-1",
        Dtag: "DBT",
        proper_des: "生科系必修，對生物有基本了解即可。",
        teacher: "楊進木、朱智瑋",
        intheclass: "板書、PPT",
        info: "楊進木老師：Sequence Alignment、Structure Alignment、BLAST、BLOSUM等基礎知識，但老師講課很跳，所以要追上老師的邏輯需要蠻全神貫注的(?)，作業不難、但很麻煩，有一份要配合BLOSUM去手動算sequence alignment最佳路徑（動態規劃），手動算真的蠻麻煩的，但考試會考。<br>\n朱智瑋老師：教得很數學，不太好懂，也會講一些矩陣（線代）的東西。但還是會講一些楊老師講到的重複的東西。然後他當時也帶我們一起看一篇paper（CATH 資料庫），但身邊的人似乎沒有很懂（我也是），但就是有基本概念這樣。<br>",
        score_des: "兩次考試，數份作業。",
        futurework: "可以對生物資訊、結構生物有興趣可以繼續鑽研。楊老師的「結構生物資訊」會教很多一模一樣的東西。",
        cross_des: "生物資訊/計算生物",
        link: "https://timetable.nycu.edu.tw/?r=main/crsoutline&Acy=107&Sem=1&CrsNo=1580&lang=zh-tw",
        author: "chiatzu"
        },
        {
        course: "生物資訊程式設計",
        eng_course: "Bioinfoprogramming",
        year: "107-1",
        Dtag: "DBT",
        proper_des: "不用有程式基礎。不怕晚下課、會想很認真跟著老師、聽從老師學習的人",
        teacher: "羅惟正",
        intheclass: "PPT、在電腦教室上課",
        info: "以PHP為語言基礎，從最基礎的字串到陣列、迴圈、條件判斷，把這些程式基本觀念上完以後，就大概過了2/3學期了。老師上課上得很扎實，也會針對程式效率教學，但就是會蠻常晚下課，但還算值得。<br>\n後1/2教CD-HIT、BLAST、TM-Align等一些生物資訊工具，也會教網頁設計，期末希望可以使用網頁、並配合這些工具，做出一個動態網站。<br>\n總結來說其實蠻有趣的，能實作出一個網站蠻厲害、很有成就感。\n\nBTW但似乎老師沒有特別高的意願再開課了。（且每一屆人數越收越少）",
        score_des: "兩次上機考、一份期末專題",
        futurework: "生物人可以不再害怕程式，多選一些不一樣的選修課程去學習",
        cross_des: "生物資訊/計算生物",
        link: "https://timetable.nycu.edu.tw/?r=main/crsoutline&Acy=107&Sem=1&CrsNo=5700&lang=zh-tw",
        author: "chiatzu"
        },
        {
        course: "生物統計",
        eng_course: "biostatistic",
        year: "108-1",
        Dtag: "DBT",
        proper_des: "任何人都可以修～",
        teacher: "王維菁",
        intheclass: "老師會給講義，會照著講義上課。",
        info: "老師人很好，授課也非常詳細（我自己是有一點點不太習慣+聽不懂她的表達，但大部分同學好像還好）。作業不難，考試也不難（都是作業的變形）。認真考試、認真寫作業就可以拿高分。",
        score_des: "期中考、期末考、數份作業。",
        futurework: "可以修他下學期開的「統計應用方法」，用R語言將統計知識活用；也學習更進階的統計知識。",
        cross_des: "基礎學科",
        link: "https://timetable.nycu.edu.tw/?r=main/crsoutline&Acy=108&Sem=1&CrsNo=5713&lang=zh-tw",
        author: "chiatzu"
        },
        {
        course: "計算生物實驗",
        eng_course: "ComputationalBiologyLab",
        year: "108-2",
        Dtag: "DBT",
        proper_des: "有生物基礎知識、有計算生物基礎知識較佳。",
        teacher: "陳亭妏、林勇欣",
        intheclass: "PPT、搭配上機實作。",
        info: "這門課過去都是林勇欣老師、曲在雯老師、尤禎祥老師在輪替，這是第一次由陳亭妏老師上上半學期。<br>\n陳亭妏老師：上Linux / Linux的一點ShellScript / Docker，每個禮拜都有小作業（不難，上課有認真都會），期中報告要使用Docker 包一個tool。（但Docker部分我沒有聽得很懂就是了QQQQ）\n林勇欣老師：教sequence alignment、演化樹關係等，跟計算生物概論有點類似，只是會實際使用excel操作（比較演化觀點一點），老師上課會帶很多思考，我覺得蠻棒的。因為當時剛好開始有疫情，期末報告就是做SARS-COV-2的Codon Usage，然後去衍伸一些討論。我自己覺得期末報告很有趣，因為很符合時事，越做越興奮，雖然沒什麼結果，但老師也會很積極給你研究方向，是一個蠻好的實作經驗。",
        score_des: "沒有考試。兩次期中、期末報告。",
        futurework: "第一次認識Docker，後來發現這個技術蠻重要蠻廣用的，之後看到這個名詞會比較有概念，",
        cross_des: "生物資訊/計算生物",
        link: "https://timetable.nycu.edu.tw/?r=main/crsoutline&Acy=108&Sem=2&CrsNo=5698&lang=zh-tw",
        author: "chiatzu"
        }
] //CourseList